---
name: "Dokku management"
description: "Github Action for managing apps on a Dokku instance"
author: "scflode"
branding:
  icon: "cloud"
  color: "orange"
inputs:
  branch:
    description: "The branch to deploy when pushing to Dokku (default: master)"
    required: false
    default: "master"
  ci_branch_name:
    description: "The command to run for the action (default: detected from GITHUB_REF)"
    required: false
    default: ""
  ci_commit:
    description: "The commit sha that will be pushed (default: detected from GITHUB_SHA)"
    required: false
    default: ""
  command:
    description: "The command to run for the action (default: deploy)"
    required: false
    default: "deploy"
  git_push_flags:
    description: "A string containing a set of flags to set on push"
    required: false
    default: ""
  git_remote_url:
    description: "The dokku app's git repository url (in SSH format)"
    required: true
  review_app_name:
    description: "The name of the review app to create or destroy"
    required: false
    default: ""
  ssh_host_key:
    description: "The results of running `ssh-keyscan -t rsa $HOST`"
    required: false
    default: ""
  ssh_private_key:
    description: "A private SSH key that has push acces to your Dokku instance"
    required: true
  custom_dockerfile_location:
    description: "A custom relative path to the Dockerfile"
    required: false
  letsencrypt_email:
    description: "Email address to use for letsencrypt"
    required: false
  port_mapping:
    description: "A Dokku style port mapping like http:80:5000"
    required: false
  databases:
    description: "Databases that should be available and linked, e.g. databaseName1:ALIAS1 databaseName2:ALIAS2"
    required: false
  app_config:
    description: "Configuration values (non-sensible) for the app, e.g. APP_ENV=prod"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  entrypoint: "/bin/dokku-deploy"
  post-entrypoint: "/bin/dokku-unlock"
  post-if: cancelled()
  env:
    BRANCH: ${{ inputs.branch }}
    CI_BRANCH_NAME: ${{ inputs.ci_branch_name }}
    CI_COMMIT: ${{ inputs.ci_commit }}
    COMMAND: ${{ inputs.command }}
    GIT_PUSH_FLAGS: ${{ inputs.git_push_flags }}
    GIT_REMOTE_URL: ${{ inputs.git_remote_url }}
    REVIEW_APP_NAME: ${{ inputs.review_app_name }}
    SSH_HOST_KEY: ${{ inputs.ssh_host_key }}
    SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
    CUSTOM_DOCKERFILE_LOCATION: ${{ inputs.custom_dockerfile_location }}
    LETSENCRYPT_EMAIL: ${{ inputs.letsencrypt_email }}
    PORT_MAPPING: ${{ inputs.port_mapping }}
    DATABASES: ${{ inputs.databases }}
    APP_CONFIG: ${{ inputs.app_config }}

